# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Viral-Bible-Ios' do

pod 'AWSS3', '~> 2.1.0'
pod 'MBProgressHUD'

end

target 'Viral-Bible-IosTests' do

end

